name: iban_to_bic
description: Determines the SWIFT BIC of any AT, BE, DE, LT, LU or NL IBAN.
version: 0.0.8
homepage: https://github.com/xonaman/flutter_iban_to_bic

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  html: ^0.15.4
  http: ^1.2.1
  path: ^1.9.0
  flutter_iban_tools: ^0.1.2
  excel: ^4.0.3
  equatable: ^2.0.5
  charset: ^2.0.1
  collection: ^1.18.0

dev_dependencies:
  flutter_lints: ^2.0.3