name: iban_to_bic
description: Determines the SWIFT BIC of an IBAN.
version: 0.0.3
homepage: https://github.com/xonaman/flutter_iban_to_bic

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  iban: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - res/datasets/